apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calf-frontend
  namespace: argocd
spec:
  project: anton-apps
  source:
    path: base/calf-frontend
    helm:
      valueFiles:
        - /staging/calf-frontend/values.yaml
    repoURL: https://github.com/KostyalBalint/anton-apps.git
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: anton-apps
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true